DefaultContentLanguage = "es"
baseURL = "https://3layers.host/"
title = "3Layers Host"
enableRobotsTXT = true

[params]
company = "3Layers"
version = "v1.10"
logo = "images/logo.jpg"
home = "Inicio"
homeurl = "/"
blog = "Blog"
blogurl = "/blog/"
socialfacebook = "/images/facebook.png"
socialfacebooklink = "https://www.facebook.com/3Layershost"
socialinstagram = "/images/instagram.png"
socialinstagramlink = "https://www.instagram.com/3layershost/"
sociallinkedin = "/images/linkedin.png"
sociallinkedinlink = "https://www.linkedin.com/company/3layershost"
socialtwitter = "/images/twitter.png"
socialtwitterlink = "https://twitter.com/3layershost"
googlemapembed="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15137.012157698788!2d-69.955313!3d18.472194!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xc7ca2d0d7f4ec684!2s3Layers%20Host!5e0!3m2!1sen!2sdo!4v1587093523164!5m2!1sen!2sdo"
googlemaplink="https://www.google.com/maps/place/3Layers+Host/@18.472194,-69.955313,15z/data=!4m5!3m4!1s0x0:0xc7ca2d0d7f4ec684!8m2!3d18.4721937!4d-69.9553129?hl=en-US"
weight = 100

[[menu.main]]
  identifier = "hosting"
  title = "Alojamiento"
  url = "/hosting/"
  weight = 200
  [[menu.main]]
      identifier = "hosting1"
      title = "Alojamiento Compartido"
      url = "/hosting/hosting1/"
      parent = "hosting"
      weight = 210
  [[menu.main]]
      identifier = "hosting2"
      title = "Alojamiento VPS"
      url = "/hosting/hosting2/"
      parent = "hosting"
      weight = 220
  [[menu.main]]
      identifier = "hosting3"
      title = "Alojamiento Dedicado"
      url = "/hosting/hosting3/"
      parent = "hosting"
      weight = 230
  [[menu.main]]
      identifier = "hosting4"
      title = "Correo Electrónico"
      url = "/hosting/hosting4/"
      parent = "hosting"
      weight = 240
[[menu.main]]
  identifier = "ssl"
  title = "SSL"
  url = "/ssl/"
  weight = 300
  [[menu.main]]
      identifier = "ssl1"
      title = "SSL Dominio (DV)"
      url = "/ssl/ssl1/"
      parent = "ssl"
      weight = 310
  [[menu.main]]
      identifier = "ssl2"
      title = "Validación Negocio (OV)"
      url = "/ssl/ssl2/"
      parent = "ssl"
      weight = 320
  [[menu.main]]
      identifier = "ssl3"
      title = "Validación Extendida (EV)"
      url = "/ssl/ssl3/"
      parent = "ssl"
      weight = 330
  [[menu.main]]
      identifier = "ssl4"
      title = "Wildcard SSL "
      url = "/ssl/ssl4/"
      parent = "ssl"
      weight = 340     
[[menu.main]]
  identifier = "suites"
  title = "Suites"
  url = "/suites/"
  weight = 400
  [[menu.main]]
      identifier = "office"
      title = "Microsoft Office 365"
      url = "/suites/microsoft-office-365/"
      parent = "suites"
      weight = 410
  [[menu.main]]
      identifier = "gsuite"
      title = "Google G-Suite"
      url = "/suites/google-g-suite/"
      parent = "suites"
      weight = 420
[[menu.main]]
  identifier = "services"
  title = "Servicios"
  url = "/migration/"
  weight = 500
  [[menu.main]]
    identifier = "domain"
    title = "Dominios de Internet"
    url = "/domain/"
    parent = "services"
    weight = 510
  [[menu.main]]
    identifier = "marketing"
    title = "Mercadeo Digital"
    url = "/services/digital-marketing/"
    parent = "services"
    weight = 520
  [[menu.main]]
    identifier = "newsletter"
    title = "Boletín informativo"
    url = "/services/newsletter"
    parent = "services"
    weight = 530
  [[menu.main]]
    identifier = "migration"
    title = "Migraciones"
    url = "/services/migraciones"
    parent = "services"
    weight = 540
  [[menu.main]]
    identifier = "archive"
    title = "Archivado"
    url = "/services/archivadoemail"
    parent = "services"
    weight = 550
  [[menu.main]]
    identifier = "support"
    title = "Soporte Técnico"
    url = "/services/soporte-tecnico/"
    parent = "services"
    weight = 560
[[menu.main]]
  identifier = "blog"
  title = "Blog"
  url = "/blog/"
  weight = 600
[[menu.main]]
  identifier = "contact"
  title = "Contacto"
  url = "/contact/"
  weight = 700