baseURL = "https://3layers.host/"
title = "3 Layers"
enableRobotsTXT = true

[params]
company = "3 Layers"
home = "Inicio"
homeurl = "/"
weight = 10

[[menu.main]]
  identifier = "domain"
  title = "Dominio"
  url = "/domain/"
  weight = 20
[[menu.main]]
  identifier = "hosting"
  title = "Alojamiento"
  url = "/hosting/"
  weight = 30
  [[menu.main]]
      identifier = "hosting1"
      title = "Alojamiento Compartido"
      url = "/hosting/hosting1/"
      parent = "hosting"
      weight = 31
  [[menu.main]]
      identifier = "hosting2"
      title = "Alojamiento Dedicado"
      url = "/hosting/hosting2/"
      parent = "hosting"
      weight = 32
  [[menu.main]]
      identifier = "hosting3"
      title = "Alojamiento Premium"
      url = "/hosting/hosting3/"
      parent = "hosting"
      weight = 33
[[menu.main]]
  identifier = "ssl"
  title = "SSL"
  url = "/ssl/"
  weight = 40
  [[menu.main]]
      identifier = "ssl1"
      title = "SSL de Dominio"
      url = "/en/ssl/ssl1/"
      parent = "ssl"
      weight = 41
  [[menu.main]]
      identifier = "ssl2"
      title = "Validación de Negocio"
      url = "/en/ssl/ssl2/"
      parent = "ssl"
      weight = 42
  [[menu.main]]
      identifier = "ssl3"
      title = "Validación Extendida"
      url = "/en/ssl/ssl3/"
      parent = "ssl"
      weight = 43
  [[menu.main]]
      identifier = "ssl4"
      title = "Wildcard SSL"
      url = "/en/ssl/ssl4/"
      parent = "ssl"
      weight = 44
[[menu.main]]
  identifier = "blog"
  title = "Blog"
  url = "/blog/"
  weight = 50
[[menu.main]]
  identifier = "contact"
  title = "Contacto"
  url = "/contact/"
  weight = 60