backend:
  name: git-gateway
  branch: master 
media_folder: static/images
public_folder: /images
collections:
- name: 'blog' # Used in routes, e.g., /admin/collections/blog
  label: 'Blog' # Used in the UI
  folder: 'content/blog' # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter      
    - {label: 'Title', name: 'title', widget: 'string'}
    - {label: 'SubTitle', name: 'subtitle', widget: 'string'}
    - {label: 'Publish Date', name: 'date', widget: 'datetime'}
    - {label: 'Draft', name: 'draft', widget: 'boolean', default: true}
    - {label: 'Site Map', name: 'sitemap', widget: 'boolean', default: true}
    - {label: 'Featured Image', name: 'thumbnail', widget: 'image'}
    - {label: 'Author', name: 'author', widget: 'string', default: 'Henry Pimentel'}
    - {label: 'Body', name: 'body', widget: 'markdown'}
- name: 'hosting' 
  label: 'Hosting' 
  folder: 'content/hosting' 
  create: false
  slug: '{{slug}}'
  fields:       
    - {label: 'Title', name: 'title', widget: 'string'}
    - {label: 'SubTitle', name: 'subtitle', widget: 'string'}
    - {label: 'Publish Date', name: 'date', widget: 'datetime'}
    - {label: 'Draft', name: 'draft', widget: 'boolean', default: true}
    - {label: 'Site Map', name: 'sitemap', widget: 'boolean', default: true}
    - {label: 'Featured Image', name: 'thumbnail', widget: 'image'}
    - {label: 'Icon', name: 'icon', widget: 'image'}
    - {label: 'Descriptión', name: 'description', widget: 'string'}
    - {label: 'URL de la Página', name: 'pageurl', widget: 'string'}
    - {label: 'SubTitle', name: 'subtitle', widget: 'number'}      
    - {label: 'Body', name: 'body', widget: 'markdown'}