---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/hosting
  label: Hosting
  create: all
  match: "**/*"
- type: directory
  path: content/domain
  label: Domain
  create: all
  match: "**/*"
- type: directory
  path: content/promotion
  label: Promotion
  create: all
  match: "**/*"
- type: directory
  path: content/hero
  label: Hero
  create: all
  match: "**/*"
- type: directory
  path: content/panel
  label: Panel
  create: all
  match: "**/*"
- type: directory
  path: content/faq
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/testimonial
  label: Testimonial
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.56.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.56.1
